version: '3'
services:
  elasticsearch:
    container_name: els
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - elastic

  app1:
    build: .
    container_name: app1
    environment:
      - APP_NAME=App1
    ports:
      - "3001:8080"
    networks:
      - elastic

  app2:
    build: .
    container_name: app2
    environment:
      - APP_NAME=App2
    ports:
      - "3002:8080"
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
